--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: grocery
    version: v1
  name: grocery
spec: 
  ports: 
    - 
      name: http
      port: 9092
      targetPort: 9092
  selector: 
    app: grocery
    version: v1
  type: NodePort