spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:postgresql://${postgres.db.host}:${postgres.db.port}/testdb
    username: postgres
    password: password
  jpa:
    properties:
       hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          show_sql: true

 

  #  datasource:
  #  url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1"
  #  username: sa
  #  password: 
  #  driver-class-name: org.h2.Driver
    
    
    
         
  #jpa:
  #  show-sql: true
 
   

